#!/usr/bin/env bash
#Display nbrs from 1 to 20 wz special msg for iterations
counter=1
while [ "$counter" -le 20 ]; do
	case $counter in
		4)
			echo "$counter bad luck from China"	
			;;
		9)
			echo "$counter bad luck from Japan"		
			;;
		17)
			echo "$counter bad luck from Italy"	
			;;
		*)
			echo "$counter"
			;;
	esac
	((counter++))
done
